import Head from 'next/head'
import {GetServerSideProps, NextPage} from "next";
import {fetchCategories} from "../http";
import {AxiosResponse} from "axios";
import {ICategory, ICollectionResponse} from "../types";
import Tabs from "../components/Tabs";

interface IPropTypes {
    categories : {
        items : ICategory[]
    }
}


const Home: NextPage<IPropTypes> = ({categories}) =>{

    console.log("categories", categories)
    return(
        <div>
            <Head>
                <title>Coder's Blog Homepage</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="stylesheet" href="/favicon.ico"/>
            </Head>
            <Tabs categories={categories.items}/>
            <main>
                <h1>This is coder's blog</h1>
            </main>
        </div>
    )
}


export const getServerSideProps: GetServerSideProps =  async () =>{
    // fetch categories
    const {data: categories} : AxiosResponse<ICollectionResponse<ICategory[]>> = await fetchCategories();

    console.log("categories", categories)
    return {
        props: {
            categories : {
                items : categories.data
            }
        }
    }
}

export default Home
